### ISSUE TITLE
"Day" dropdown is cut off in advanced search

### ISSUE THREAD

**Issue by benaltair** [bahaistudies/jbs#50]
https://journal.bahaistudies.ca/online/search/search
![image](https://user-images.githubusercontent.com/17771229/116127808-1944e380-a67d-11eb-90da-44c1622fcefa.png)

**Comment by benaltair** [comment]
Should be fixed for now by applying a min-width to any of the select components that reference days:
```css
select.form-control[name*=Day] {
    min-width: 8ch;
}
```
