### ISSUE TITLE
Registration form fields leave container

### ISSUE THREAD

**Issue by benaltair** [bahaistudies/jbs#51]
![image](https://user-images.githubusercontent.com/17771229/116142690-10f5a400-a68f-11eb-9e63-6b11b1dccd88.png)

**Comment by benaltair** [comment]
Looks like https://github.com/bahaistudies/jbs/commit/57522b1d3a0a2aac3f6ec013b263b1979144ac70 hard broke the CSS compilation. My guess is that it's either a syntax error on my part (can't see anything at first glance) or the LESS processor didn't like custom properties? 
![image](https://user-images.githubusercontent.com/17771229/116143774-68484400-a690-11eb-94ad-ef1aaefe890a.png)

**Comment by benaltair** [comment]
Had some issues with LESS processing again, as it was trying to pre-compute CSS `calc()` functions which defeats the purpose of `calc()` in the first place. By implementing [this fix](https://github.com/less/less.js/issues/974#issuecomment-9229470) it is now taking the calculation literally without pre-processing it.
```css
.form-control {
    all: revert;
    padding: 0.5em;
    width: calc(100% - 0.5em * 2);
    border-color: lightgrey;
    border: 1px solid #ced4da;
    border-radius: 0.3em;
    font-size: 1em;
}
```
![image](https://user-images.githubusercontent.com/17771229/116155834-85d0da00-a69f-11eb-98ff-aa80072fb459.png)
